### ISSUE TITLE
Make dying send you back to the last checkpoint

### ISSUE THREAD

**Issue by MisterE123** [BuckarooBanzay/super_sam#37]

**Comment by MisterE123** [comment]
You can also add player death animation, as well as make the player jump up into the air and fall back when they die

**Comment by BuckarooBanzay** [comment]
This was the case before i started to implement a "lounge/start" platform that you can use to jump to other level-groups.

Currently the start platform should resemble something like that:
![](https://i.etsystatic.com/10178728/r/il/289409/720708044/il_794xN.720708044_8vd9.jpg)

And from there you jump into the "level-groups", if you die you should get back to the start-platform again if you ask me (or else it would be too easy ;)

> You can also add player death animation, as well as make the player jump up into the air and fall back when they die

That sounds cool, not sure if the engine would allow me to do that smoothly

**Comment by MisterE123** [comment]
> That sounds cool, not sure if the engine would allow me to do that smoothly

ofc it would :p the engine does give pretty good control. you can use an attachment entity in this case

**Comment by MisterE123** [comment]
> And from there you jump into the "level-groups", if you die you should get back to the start-platform again if you ask me (or else it would be too easy ;)

eh, for longer levels, it would be better to actually have checkpoints, I think. but for shorter levels, you're right

**Comment by BuckarooBanzay** [comment]
implemented partial checkpoints with the overview/lounge thing, closing this
