### ISSUE TITLE
Make teleporters teleport when you press sneak while on them, instead of doing it automatically.

### ISSUE THREAD

**Issue by MisterE123** [BuckarooBanzay/super_sam#41]
Also, just get rid of teleporters; use doors instead

**Comment by BuckarooBanzay** [comment]
Eh, if i would do that it has to be explained somewhere, otherwise i don't think most players would get it :/

> Also, just get rid of teleporters; use doors instead

Doors you can click and get teleported or do you mean to place the levels near each others separated by doors? :thinking:

**Comment by MisterE123** [comment]
ofc, you would explain in an hud, asewell as explain other things

for doors, you woul. enter the door to be teleported. returning from a level puts you just outside the door.

**Comment by BuckarooBanzay** [comment]
> Also, just get rid of teleporters; use doors instead

works different now, doors are not an option in multiplayer
